baseURL = "/"
languageCode = "en-us"
title = "AxioDL"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "URDE is an attempt to recreate the engine for Retro Studios’ GameCube and Wii games, including the Metroid Prime series and Donkey Kong Country Returns. The goal is to have the games run natively on Linux, Windows, and macOS. Effort has been taken to ensure the behavior is as close to the originals as possible."
  subtitle = "AxioDL"
  keywords = "homepage, open-source, software, metroid prime, retro studios, urde, hecl"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"


[languages]
  [languages.en]
    title = "URDE"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "AxioDL"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identiier = "discord"
    name = "Discord"
    url = "https://discord.gg/AMBVFuf"
  [[menu.main]]
    identifier = "releases"
    name       = "Releases"
    url        = "https://releases.axiodl.com"

